/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/
#include <project.h>
#include "led.h"
#include "Alert.h"

void AT_init(void);
void StackEventHandler(uint32 event, void* eventParam);


int main()
{
    CYBLE_API_RESULT_T apiResult;
    
     AT_init();
     apiResult = CyBle_Start(StackEventHandler); 
    if(apiResult != CYBLE_ERROR_OK)
    {
        CYASSERT(0);
    }
     CyGlobalIntEnable; 
    
     CyBle_IasRegisterAttrCallback(IasEventHandler);
    
    for(;;)
    {

        CyBle_ProcessEvents();
        switch(alertLevel)
        {
            case NO_ALERT:
            LED_OFF(B);
            break;

            case MILD_ALERT:
            LED_ON(B);
            break;

            case HIGH_ALERT:
            LED_OFF(B);
            break;
        } 
    }
}

void AT_init(void)
{
    UART_AT_Start();
    UART_AT_SCB_IRQ_Start();
    UART_AT_UartPutString("Test for AT");
  #if 0
    LED(R,OFF);
    LED(G,OFF);
    LED(B,OFF);
  #else 
    LED_OFF(R);
    LED_OFF(G);
    LED_OFF(B);
   #endif
    //CyDelay(1000u);
  }


/*******************************************************************************
* Function Name: StackEventHandler
********************************************************************************
*
* Summary:
*  This is an event callback function to receive events from the BLE Component.
*
* Parameters:
*  uint8 event:       Event from the CYBLE component
*  void* eventParams: A structure instance for corresponding event type. The
*                     list of event structure is described in the component
*                     datasheet.
*
* Return:
*  None
*
*******************************************************************************/
void StackEventHandler(uint32 event, void *eventParam)
{
    switch(event)
    {
        /* Mandatory events to be handled by Find Me Target design */
        case CYBLE_EVT_STACK_ON:
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED:
            /* Start BLE advertisement for 30 seconds and update link
             * status on LEDs */
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            LED_ON(G);//ADV
            alertLevel = NO_ALERT;
            break;

        case CYBLE_EVT_GAP_DEVICE_CONNECTED:
            /* BLE link is established */
            LED_OFF(G);///ADV
            LED_OFF(R);//DISCONNECTED
            break;

        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:
            if(CyBle_GetState() == CYBLE_STATE_DISCONNECTED)
            {
                /* Advertisement event timed out, go to low power
                 * mode (Stop mode) and wait for device reset
                 * event to wake up the device again */
                 LED_OFF(G);///ADV
                 LED_ON(R);//DISCONNECTED
                 CySysPmSetWakeupPolarity(CY_PM_STOP_WAKEUP_ACTIVE_HIGH);
                 CySysPmStop();
               
                /* Code execution will not reach here */
            }
            break;

        /* Other events that are generated by the BLE Component that
         * are not required for functioning of this design */
        /**********************************************************
        *                       General Events
        ***********************************************************/
        case CYBLE_EVT_HARDWARE_ERROR:    /* This event indicates that some internal HW error has occurred. */
            break;

        case CYBLE_EVT_HCI_STATUS:
            break;

        /**********************************************************
        *                       GAP Events
        ***********************************************************/
        case CYBLE_EVT_GAP_AUTH_REQ:
            break;

        case CYBLE_EVT_GAP_PASSKEY_ENTRY_REQUEST:
            break;

        case CYBLE_EVT_GAP_PASSKEY_DISPLAY_REQUEST:
            break;

        case CYBLE_EVT_GAP_AUTH_COMPLETE:

            break;
        case CYBLE_EVT_GAP_AUTH_FAILED:

            break;

        case CYBLE_EVT_GAP_ENCRYPT_CHANGE:
            break;

        case CYBLE_EVT_GAPC_CONNECTION_UPDATE_COMPLETE:
            break;

        /**********************************************************
        *                       GATT Events
        ***********************************************************/
        case CYBLE_EVT_GATT_CONNECT_IND:
            break;

        case CYBLE_EVT_GATT_DISCONNECT_IND:
            break;

        case CYBLE_EVT_GATTS_XCNHG_MTU_REQ:
            break;

        case CYBLE_EVT_GATTS_READ_CHAR_VAL_ACCESS_REQ:
            break;

        /**********************************************************
        *                       Other Events
        ***********************************************************/
        case CYBLE_EVT_PENDING_FLASH_WRITE:
            break;

        default:
            break;
    }
}





////////////////Interrupt///////////////////////////
/*******************************************************************************
* Function Name: UART_AT_SCB_IRQ_Interrupt
********************************************************************************
*
* Summary:
*
* Parameters:  
*   None
*
* Return:
*   None
*
*******************************************************************************/
CY_ISR(UART_AT_SCB_IRQ_Interrupt)
{
    #ifdef UART_AT_SCB_IRQ_INTERRUPT_INTERRUPT_CALLBACK
        UART_AT_SCB_IRQ_Interrupt_InterruptCallback();
    #endif /* UART_AT_SCB_IRQ_INTERRUPT_INTERRUPT_CALLBACK */ 

    /*  Place your Interrupt code here. */
    /* `#START UART_AT_SCB_IRQ_Interrupt` */ 
    UART_AT_ClearRxInterruptSource(UART_AT_INTR_RX_NOT_EMPTY);
    if(UART_AT_GetRxInterruptSourceMasked()&UART_AT_INTR_RX_NOT_EMPTY)
    {
        uint32 ReceviceData=0;
        ReceviceData=UART_AT_SpiUartReadRxData();
        LED_ON(ReceviceData);
        UART_AT_UartPutChar((uint8_t)ReceviceData);
    }
    UART_AT_SpiUartClearRxBuffer();  
    /* `#END` */
}
  


